name: HoneyXBadger CI

on:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Generate Typechain
        run: npm run generate
      - name: Run tests
        id: step_test
        run: npm run test
      - name: Create commit comment success
        if: ${{ steps.step_test.outcome == 'success' }}
        uses: peter-evans/commit-comment@v1
        with:
          body: "유닛테스트를 통과하였습니다 ✅"
      - name: Create commit comment fail
        if: ${{ steps.step_test.outcome != 'success' }}
        uses: peter-evans/commit-comment@v1
        with:
          body: "유닛테스트를 통과하지 못했습니다 ❌"
    
    
